name: main
on: [ push ]
env:
  MELI_SITE: "ff198cec-9c89-4030-b83e-7c2255657ce1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: "build"
        run |
          npm ci
          npm run build
      - name: "publish"
        run: |
          npx @getmeli/cli@next upload \
            --url https://plat.hardwarepanic.com \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA" \
            ./public
        env:
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
